export const GameMsg = {
    START_GAME: "START_GAME",
    JOIN_GAME: "JOIN_GAME",
    LEAVE_GAME: "LEAVE_GAME",
    GAME_PLAY: "GAME_PLAY",
    UPDATE_GAME_STATE : "UPDATE_GAME_STATE",
    ON_GAME_SESSION_CREATED: "ON_GAME_SESSION_CREATED",
    ON_GAME_STARTED: "ON_GAME_STARTED",
    ON_GAME_INIT: "ON_GAME_INIT",
    ON_USER_CONNECTED: "ON_USER_CONNECTED",
    ON_USER_DISCONNECTED: "ON_USER_DISCONNECTED",
    ON_GAME_OVER: "ON_GAME_OVER"
  }

